### ISSUE TITLE
"wmCurrentDesktopNr" ignored by some applications

### ISSUE THREAD

**Issue by MaxSchambach** [johannesjo/linux-window-session-manager#21]
## Your Environment
* Version used: 2.1.20
* Operating System and version: ArchLinux 4.15.7
* Desktop Environment: GNOME shell 3.26.2
* Node version: 9.8.0

## Expected Behavior
Application is opened on (virtual) Desktop with number ``"wmCurrentDesktopNr"`` as specified in the session`s config file.

## Current Behavior
For most applications, this works. Some applications always work on the current desktop. Observed with e.g. Gitkraken.

## Steps to Reproduce (for bugs)
Save a session with applications being on different virtual desktops.
Restore the session.

How do I debug this? Would be glad to help find the problem.

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. I'm assuming that this caused by the application not being correctly to X11. If that's the case, there is not much we can do. If you want to dig deeper into this, I would suggest playing around with [xdotool](https://wiki.ubuntuusers.de/xdotool/) and [wmctrl](https://wiki.ubuntuusers.de/wmctrl/). If it works there, than we can make it work here probably too.

**Comment by MaxSchambach** [comment]
I'm using X11.
I'll play around with the aforementioned tools when I have some time. 
Thanks!
