### ISSUE TITLE
Doesn't work with workspaces - all windows are restored to first ws

### ISSUE THREAD

**Issue by theWebalyst** [johannesjo/linux-window-session-manager#48]
## Your Environment
* Version used: not sure how to find this (lwsm -v / --version don't do anything)
* Operating System and version: Ubuntu 19.04
* Desktop Environment: Gnome 3.32.1
* Node version: 8.11.3
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): 

## Expected Behavior
Restoring a saved session should restore apps/windows to the 'workspace' they were in when saved.

The README says it works with virtual desktops, so I was hoping this means with Gnome workspaces, but it seems they may be different?

## Current Behavior
All apps/windows are restored to the first workspace, rather than the ones from where they were saved.

**Comment by johannesjo** [comment]
Thanks for reporting! I'll check this next week!

**Comment by theWebalyst** [comment]
:+1: For interest I found a session script [here](http://blog.thewebsitepeople.org/2013/07/gnome-session-save-and-restore/) which works with workspaces. It only saves/restores a single session, but does this pretty well.

**Comment by johannesjo** [comment]
I am unable to reproduce this issue.  Just checked with the same Ubuntu Version and Gnome Version 3.32.0. Could you please try installing the latest version via
```
npm update -g linux-window-session-manager
```
?

Please make also sure that you are not using Wayland.

**Comment by theWebalyst** [comment]
I'm using yarn so `yarn global upgrade linux-window-session-manager` gives me: linux-window-session-manager@2.1.31

Trying again, looks like no difference. I see it stops when it tries to start Atom editor:

```
Status: "atom.Atom" is running: false 3 0
Starting: atom.desktop
Wait for all applications to start
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn x-terminal-emulator.desktop ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I'll try again without Atom running. Same error (ENOENT):

```
Status: "x-terminal-emulator.X-terminal-emulator" is running: false 18 0
Starting: x-terminal-emulator.desktop
Wait for all applications to start
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn x-terminal-emulator.desktop ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
By this point it has already started a dozen instances of `x-terminal-emulator.desktop` so it is not a problem with the particular app, but perhaps a resource issue?

Oh, BTW I'm using X11 not Wayland.

**Comment by johannesjo** [comment]
@theWebalyst did you try using the troubleshooting guide? Seems like you need to provide a custom mapping for that app.

**Comment by theWebalyst** [comment]
Why do you think it is the particular app? It loads that so fine before the error:

> By this point it has already started a dozen instances of x-terminal-emulator.desktop so it is not a problem with the particular app, but perhaps a resource issue?

**Comment by johannesjo** [comment]
I just tested it with atom as well. Seems to work fine. I tried xterm (I am assuming you are using that) and  lwsm is unable to guess it's desktop file path, so you need to manually provide it in your settings. Please refer to the troubleshooting guide in the readme on how to do that.

**Comment by theWebalyst** [comment]
Ok, but just to note, all of these worked before I upgraded from Ubuntu 18.10 to 19.04. In fact I think 19.04 was still able to restore the previously saved ws. I only noticed a problem when I started using multiple desktops (after the upgrade).

Thanks for your help, although for now I do have an alternative solution (noted above).

**Comment by johannesjo** [comment]
Hm that's a little weird. Might be that they changed some of the filenames for the new version? Not sure why this is the case. Glad that it works for you with the script I noticed however that it doesn't attempt to start the closed applications like lwsm does.

**Comment by theWebalyst** [comment]
It does the whole job including starting apps, but you can run it without that (default / option 0).

**Comment by johannesjo** [comment]
Ah I see! Thank you! That's interesting. Maybe they have better of saving the executable paths.

**Comment by johannesjo** [comment]
I checked the solution. They access `/proc/${processId}/cmdline` to read the executable. This might be problematic for some specific scenarios and more importantly not every user has the right to do so. I think I leave things as is.

**Comment by allentiak** [comment]
Hi, @johannesjo 
I've just bumped into this as well. I think this one should be reopened (Otherwise, I could open a new one). Details below.


## Your Environment
* Version used: 3.0.8
* Operating System and version: Debian bullseye/sid
* Desktop Environment: GNOME 3.34
* Node version: 12.6.0
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): 
Firefox (multiple windows across multiple workspaces)

## Expected Behavior
As a user,
When restoring a session,
Windows originally placed in different workspaces should be restored in their original workspaces.




## Current Behavior
As a user,
When restoring a session,
All windows originally placed in different workspaces are restored in the first workspace.


## Steps to Reproduce (for bugs)


1. Start Firefox
2. Open X new windows in Firefox
3. Distibute them across different workspaces (I used four).
4. Save the session
5. Logout
6. Login
7. When restoring the session, the different windows should be restored in their original locations.

**Comment by leozilla** [comment]
Hi, @johannesjo
I am experiencing the same issue. I really like the tool, its the best I found but this issue is almost a blocker for me.

**Your Environment**
Version used: 4.0.0
Operating System and version: Ubuntu 20.04 LTS
Desktop Environment: GNOME 3.36.2
Node version: 10.19.0
List of Applications that are open (lwsm save) or should be opened (lwsm restore):
Chrome (multiple windows across multiple workspaces), Ubuntu Terminal, Slack, IntelliJ IDEA, Sublime

**Expected Behavior
Current Behavior
Steps to Reproduce (for bugs)**
Same as reported by @allentiak [here](https://github.com/johannesjo/linux-window-session-manager/issues/48#issuecomment-583138784)

**Comment by johannesjo** [comment]
@leozilla as I can't reproduce the issue (not on my computer not on a fresh vm)  and we're using almost the same environment I really don't know what might be causing this. It might be some sort of timing issue. Have you tried adjusting the `GIVE_X11_TIME_TIMEOUT` value in your cfg?

**Comment by jjaone** [comment]
In Ubuntu 18.04, I have this exact problemm all apps and windows are restored on the first workspace not where they were when session was saved. I am on Gnome and lwsm lates version, would check the numbers if I knew how to do that.

**Comment by johannesjo** [comment]
@jjaone are you using the latest version of lwsm? If so could you please provide a little bit more detail?

**Comment by brpandey** [comment]
I got this clumping up of windows on the first ws error as well, turned out it was due to including multiple terminal windows.  (I'm on Ubuntu 18).  

If It works fine with one terminal window but not multiple then update the default config.json file
``
  "WM_CLASS_AND_EXECUTABLE_FILE_MAP": {
    "gnome-terminal-server.Gnome-terminal": "/usr/share/applications/org.gnome.T
erminal.desktop"
``
